### ISSUE TITLE
Move docs to this repo

### ISSUE THREAD

**Issue by EndBug** [emanuelescarabattoli/react-ribbons#26]
Hey, I see that there are docs at https://emanuelescarabattoli.github.io/react-ribbons/index.html, and that there is a `docs` folder in this repo (probably hosted via GH Pages)
The `docs` folder seems to only contain the built static website, so I was wondering: where is the source of the docs?

**Comment by emanuelescarabattoli** [comment]
Hi @EndBug, well, docs are in here [https://github.com/emanuelescarabattoli/react-ribbons-demo](https://github.com/emanuelescarabattoli/react-ribbons-demo). I know, it is a little bit random, when I initially created the project i was too busy to do place docs in the proper way XD

**Comment by emanuelescarabattoli** [comment]
@EndBug, now docs are in repo. Maybe i should find a way to remove dist from the repo itself, if possible (as I should do for npm package build).
